appId: com.pizzaapp
env:
    USERNAME: user@example.com
    PASSWORD: 123
---
- clearState
- launchApp
- tapOn: email
- eraseText: 100 #default is 50  
- inputText: ${USERNAME}
- tapOn: Password     # case insensitive
- eraseText: 100 #default is 50  
- inputText: ${PASSWORD}
